/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateStandaloneAdRequestTranslationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStandaloneAdRequestTranslationsInner{}

// CreateStandaloneAdRequestTranslationsInner struct for CreateStandaloneAdRequestTranslationsInner
type CreateStandaloneAdRequestTranslationsInner struct {
	// Language code, resolved to Meta's numeric locale id. Bare codes target the '(All)' umbrella (`es` = every Spanish variant); region-qualified codes target the variant (`pt_BR`, `en_GB`).
	Locale string `json:"locale"`
	// Headline for this language. Inherits the top-level `headline` when omitted.
	Headline *string `json:"headline,omitempty"`
	// Primary text for this language. Inherits the top-level `body` when omitted.
	Body *string `json:"body,omitempty"`
	// Link description for this language. Inherits the top-level `description` when omitted.
	Description *string `json:"description,omitempty"`
	// Image for this language. Inherits the ad's `imageUrl` when omitted. The feed is all-image OR all-video.
	ImageUrl *string `json:"imageUrl,omitempty"`
	// Video for this language. Inherits the ad's `video.url` when omitted. The feed is all-image OR all-video.
	VideoUrl *string `json:"videoUrl,omitempty"`
	// Poster frame for this language's video.
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`
}

type _CreateStandaloneAdRequestTranslationsInner CreateStandaloneAdRequestTranslationsInner

// NewCreateStandaloneAdRequestTranslationsInner instantiates a new CreateStandaloneAdRequestTranslationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStandaloneAdRequestTranslationsInner(locale string) *CreateStandaloneAdRequestTranslationsInner {
	this := CreateStandaloneAdRequestTranslationsInner{}
	this.Locale = locale
	return &this
}

// NewCreateStandaloneAdRequestTranslationsInnerWithDefaults instantiates a new CreateStandaloneAdRequestTranslationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStandaloneAdRequestTranslationsInnerWithDefaults() *CreateStandaloneAdRequestTranslationsInner {
	this := CreateStandaloneAdRequestTranslationsInner{}
	return &this
}

// GetLocale returns the Locale field value
func (o *CreateStandaloneAdRequestTranslationsInner) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *CreateStandaloneAdRequestTranslationsInner) SetLocale(v string) {
	o.Locale = v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetHeadline() string {
	if o == nil || IsNil(o.Headline) {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetHeadline(v string) {
	o.Headline = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetBody(v string) {
	o.Body = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetDescription(v string) {
	o.Description = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetVideoUrl() string {
	if o == nil || IsNil(o.VideoUrl) {
		var ret string
		return ret
	}
	return *o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetVideoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.VideoUrl) {
		return nil, false
	}
	return o.VideoUrl, true
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasVideoUrl() bool {
	if o != nil && !IsNil(o.VideoUrl) {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given string and assigns it to the VideoUrl field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetVideoUrl(v string) {
	o.VideoUrl = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestTranslationsInner) GetThumbnailUrl() string {
	if o == nil || IsNil(o.ThumbnailUrl) {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailUrl) {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestTranslationsInner) HasThumbnailUrl() bool {
	if o != nil && !IsNil(o.ThumbnailUrl) {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *CreateStandaloneAdRequestTranslationsInner) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

func (o CreateStandaloneAdRequestTranslationsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStandaloneAdRequestTranslationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locale"] = o.Locale
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.VideoUrl) {
		toSerialize["videoUrl"] = o.VideoUrl
	}
	if !IsNil(o.ThumbnailUrl) {
		toSerialize["thumbnailUrl"] = o.ThumbnailUrl
	}
	return toSerialize, nil
}

func (o *CreateStandaloneAdRequestTranslationsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateStandaloneAdRequestTranslationsInner := _CreateStandaloneAdRequestTranslationsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateStandaloneAdRequestTranslationsInner)

	if err != nil {
		return err
	}

	*o = CreateStandaloneAdRequestTranslationsInner(varCreateStandaloneAdRequestTranslationsInner)

	return err
}

type NullableCreateStandaloneAdRequestTranslationsInner struct {
	value *CreateStandaloneAdRequestTranslationsInner
	isSet bool
}

func (v NullableCreateStandaloneAdRequestTranslationsInner) Get() *CreateStandaloneAdRequestTranslationsInner {
	return v.value
}

func (v *NullableCreateStandaloneAdRequestTranslationsInner) Set(val *CreateStandaloneAdRequestTranslationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStandaloneAdRequestTranslationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStandaloneAdRequestTranslationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStandaloneAdRequestTranslationsInner(val *CreateStandaloneAdRequestTranslationsInner) *NullableCreateStandaloneAdRequestTranslationsInner {
	return &NullableCreateStandaloneAdRequestTranslationsInner{value: val, isSet: true}
}

func (v NullableCreateStandaloneAdRequestTranslationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStandaloneAdRequestTranslationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
