/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateWhatsAppTemplateByIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWhatsAppTemplateByIdRequest{}

// UpdateWhatsAppTemplateByIdRequest struct for UpdateWhatsAppTemplateByIdRequest
type UpdateWhatsAppTemplateByIdRequest struct {
	// WhatsApp social account ID
	AccountId string `json:"accountId"`
	// Updated template components
	Components []WhatsAppTemplateComponent `json:"components"`
}

type _UpdateWhatsAppTemplateByIdRequest UpdateWhatsAppTemplateByIdRequest

// NewUpdateWhatsAppTemplateByIdRequest instantiates a new UpdateWhatsAppTemplateByIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWhatsAppTemplateByIdRequest(accountId string, components []WhatsAppTemplateComponent) *UpdateWhatsAppTemplateByIdRequest {
	this := UpdateWhatsAppTemplateByIdRequest{}
	this.AccountId = accountId
	this.Components = components
	return &this
}

// NewUpdateWhatsAppTemplateByIdRequestWithDefaults instantiates a new UpdateWhatsAppTemplateByIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWhatsAppTemplateByIdRequestWithDefaults() *UpdateWhatsAppTemplateByIdRequest {
	this := UpdateWhatsAppTemplateByIdRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *UpdateWhatsAppTemplateByIdRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *UpdateWhatsAppTemplateByIdRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *UpdateWhatsAppTemplateByIdRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetComponents returns the Components field value
func (o *UpdateWhatsAppTemplateByIdRequest) GetComponents() []WhatsAppTemplateComponent {
	if o == nil {
		var ret []WhatsAppTemplateComponent
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *UpdateWhatsAppTemplateByIdRequest) GetComponentsOk() ([]WhatsAppTemplateComponent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Components, true
}

// SetComponents sets field value
func (o *UpdateWhatsAppTemplateByIdRequest) SetComponents(v []WhatsAppTemplateComponent) {
	o.Components = v
}

func (o UpdateWhatsAppTemplateByIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWhatsAppTemplateByIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["components"] = o.Components
	return toSerialize, nil
}

func (o *UpdateWhatsAppTemplateByIdRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"components",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateWhatsAppTemplateByIdRequest := _UpdateWhatsAppTemplateByIdRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateWhatsAppTemplateByIdRequest)

	if err != nil {
		return err
	}

	*o = UpdateWhatsAppTemplateByIdRequest(varUpdateWhatsAppTemplateByIdRequest)

	return err
}

type NullableUpdateWhatsAppTemplateByIdRequest struct {
	value *UpdateWhatsAppTemplateByIdRequest
	isSet bool
}

func (v NullableUpdateWhatsAppTemplateByIdRequest) Get() *UpdateWhatsAppTemplateByIdRequest {
	return v.value
}

func (v *NullableUpdateWhatsAppTemplateByIdRequest) Set(val *UpdateWhatsAppTemplateByIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWhatsAppTemplateByIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWhatsAppTemplateByIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWhatsAppTemplateByIdRequest(val *UpdateWhatsAppTemplateByIdRequest) *NullableUpdateWhatsAppTemplateByIdRequest {
	return &NullableUpdateWhatsAppTemplateByIdRequest{value: val, isSet: true}
}

func (v NullableUpdateWhatsAppTemplateByIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWhatsAppTemplateByIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
