/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the SendInboxMessage400ResponsePlatformError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendInboxMessage400ResponsePlatformError{}

// SendInboxMessage400ResponsePlatformError Instagram/Facebook only. Meta's own diagnostic fields for the rejected send, passed through verbatim so you can tell failure classes apart and quote them to Meta. Absent when the failure did not come from Meta.
type SendInboxMessage400ResponsePlatformError struct {
	// Meta error code
	Code *int32 `json:"code,omitempty"`
	// Meta error_subcode
	Subcode *int32 `json:"subcode,omitempty"`
	// Meta fbtrace_id, quote this in a Meta bug report
	FbtraceId *string `json:"fbtraceId,omitempty"`
	// Meta error type (e.g. OAuthException)
	Type *string `json:"type,omitempty"`
}

// NewSendInboxMessage400ResponsePlatformError instantiates a new SendInboxMessage400ResponsePlatformError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendInboxMessage400ResponsePlatformError() *SendInboxMessage400ResponsePlatformError {
	this := SendInboxMessage400ResponsePlatformError{}
	return &this
}

// NewSendInboxMessage400ResponsePlatformErrorWithDefaults instantiates a new SendInboxMessage400ResponsePlatformError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendInboxMessage400ResponsePlatformErrorWithDefaults() *SendInboxMessage400ResponsePlatformError {
	this := SendInboxMessage400ResponsePlatformError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SendInboxMessage400ResponsePlatformError) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendInboxMessage400ResponsePlatformError) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SendInboxMessage400ResponsePlatformError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *SendInboxMessage400ResponsePlatformError) SetCode(v int32) {
	o.Code = &v
}

// GetSubcode returns the Subcode field value if set, zero value otherwise.
func (o *SendInboxMessage400ResponsePlatformError) GetSubcode() int32 {
	if o == nil || IsNil(o.Subcode) {
		var ret int32
		return ret
	}
	return *o.Subcode
}

// GetSubcodeOk returns a tuple with the Subcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendInboxMessage400ResponsePlatformError) GetSubcodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Subcode) {
		return nil, false
	}
	return o.Subcode, true
}

// HasSubcode returns a boolean if a field has been set.
func (o *SendInboxMessage400ResponsePlatformError) HasSubcode() bool {
	if o != nil && !IsNil(o.Subcode) {
		return true
	}

	return false
}

// SetSubcode gets a reference to the given int32 and assigns it to the Subcode field.
func (o *SendInboxMessage400ResponsePlatformError) SetSubcode(v int32) {
	o.Subcode = &v
}

// GetFbtraceId returns the FbtraceId field value if set, zero value otherwise.
func (o *SendInboxMessage400ResponsePlatformError) GetFbtraceId() string {
	if o == nil || IsNil(o.FbtraceId) {
		var ret string
		return ret
	}
	return *o.FbtraceId
}

// GetFbtraceIdOk returns a tuple with the FbtraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendInboxMessage400ResponsePlatformError) GetFbtraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.FbtraceId) {
		return nil, false
	}
	return o.FbtraceId, true
}

// HasFbtraceId returns a boolean if a field has been set.
func (o *SendInboxMessage400ResponsePlatformError) HasFbtraceId() bool {
	if o != nil && !IsNil(o.FbtraceId) {
		return true
	}

	return false
}

// SetFbtraceId gets a reference to the given string and assigns it to the FbtraceId field.
func (o *SendInboxMessage400ResponsePlatformError) SetFbtraceId(v string) {
	o.FbtraceId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SendInboxMessage400ResponsePlatformError) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendInboxMessage400ResponsePlatformError) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SendInboxMessage400ResponsePlatformError) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SendInboxMessage400ResponsePlatformError) SetType(v string) {
	o.Type = &v
}

func (o SendInboxMessage400ResponsePlatformError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendInboxMessage400ResponsePlatformError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Subcode) {
		toSerialize["subcode"] = o.Subcode
	}
	if !IsNil(o.FbtraceId) {
		toSerialize["fbtraceId"] = o.FbtraceId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSendInboxMessage400ResponsePlatformError struct {
	value *SendInboxMessage400ResponsePlatformError
	isSet bool
}

func (v NullableSendInboxMessage400ResponsePlatformError) Get() *SendInboxMessage400ResponsePlatformError {
	return v.value
}

func (v *NullableSendInboxMessage400ResponsePlatformError) Set(val *SendInboxMessage400ResponsePlatformError) {
	v.value = val
	v.isSet = true
}

func (v NullableSendInboxMessage400ResponsePlatformError) IsSet() bool {
	return v.isSet
}

func (v *NullableSendInboxMessage400ResponsePlatformError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendInboxMessage400ResponsePlatformError(val *SendInboxMessage400ResponsePlatformError) *NullableSendInboxMessage400ResponsePlatformError {
	return &NullableSendInboxMessage400ResponsePlatformError{value: val, isSet: true}
}

func (v NullableSendInboxMessage400ResponsePlatformError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendInboxMessage400ResponsePlatformError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
