/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetAdsSearchTerms200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdsSearchTerms200Response{}

// GetAdsSearchTerms200Response struct for GetAdsSearchTerms200Response
type GetAdsSearchTerms200Response struct {
	CustomerId *string                                 `json:"customerId,omitempty"`
	Data       []GetAdsSearchTerms200ResponseDataInner `json:"data,omitempty"`
	Paging     *GetAdsSearchTerms200ResponsePaging     `json:"paging,omitempty"`
}

// NewGetAdsSearchTerms200Response instantiates a new GetAdsSearchTerms200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdsSearchTerms200Response() *GetAdsSearchTerms200Response {
	this := GetAdsSearchTerms200Response{}
	return &this
}

// NewGetAdsSearchTerms200ResponseWithDefaults instantiates a new GetAdsSearchTerms200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdsSearchTerms200ResponseWithDefaults() *GetAdsSearchTerms200Response {
	this := GetAdsSearchTerms200Response{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *GetAdsSearchTerms200Response) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdsSearchTerms200Response) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *GetAdsSearchTerms200Response) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *GetAdsSearchTerms200Response) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAdsSearchTerms200Response) GetData() []GetAdsSearchTerms200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetAdsSearchTerms200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdsSearchTerms200Response) GetDataOk() ([]GetAdsSearchTerms200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAdsSearchTerms200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetAdsSearchTerms200ResponseDataInner and assigns it to the Data field.
func (o *GetAdsSearchTerms200Response) SetData(v []GetAdsSearchTerms200ResponseDataInner) {
	o.Data = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *GetAdsSearchTerms200Response) GetPaging() GetAdsSearchTerms200ResponsePaging {
	if o == nil || IsNil(o.Paging) {
		var ret GetAdsSearchTerms200ResponsePaging
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdsSearchTerms200Response) GetPagingOk() (*GetAdsSearchTerms200ResponsePaging, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *GetAdsSearchTerms200Response) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given GetAdsSearchTerms200ResponsePaging and assigns it to the Paging field.
func (o *GetAdsSearchTerms200Response) SetPaging(v GetAdsSearchTerms200ResponsePaging) {
	o.Paging = &v
}

func (o GetAdsSearchTerms200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdsSearchTerms200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableGetAdsSearchTerms200Response struct {
	value *GetAdsSearchTerms200Response
	isSet bool
}

func (v NullableGetAdsSearchTerms200Response) Get() *GetAdsSearchTerms200Response {
	return v.value
}

func (v *NullableGetAdsSearchTerms200Response) Set(val *GetAdsSearchTerms200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdsSearchTerms200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdsSearchTerms200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdsSearchTerms200Response(val *GetAdsSearchTerms200Response) *NullableGetAdsSearchTerms200Response {
	return &NullableGetAdsSearchTerms200Response{value: val, isSet: true}
}

func (v NullableGetAdsSearchTerms200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdsSearchTerms200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
