/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the CreateInboxConversation404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInboxConversation404Response{}

// CreateInboxConversation404Response struct for CreateInboxConversation404Response
type CreateInboxConversation404Response struct {
	Error *string `json:"error,omitempty"`
	Code  *string `json:"code,omitempty"`
}

// NewCreateInboxConversation404Response instantiates a new CreateInboxConversation404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInboxConversation404Response() *CreateInboxConversation404Response {
	this := CreateInboxConversation404Response{}
	return &this
}

// NewCreateInboxConversation404ResponseWithDefaults instantiates a new CreateInboxConversation404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInboxConversation404ResponseWithDefaults() *CreateInboxConversation404Response {
	this := CreateInboxConversation404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateInboxConversation404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversation404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateInboxConversation404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateInboxConversation404Response) SetError(v string) {
	o.Error = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateInboxConversation404Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversation404Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateInboxConversation404Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CreateInboxConversation404Response) SetCode(v string) {
	o.Code = &v
}

func (o CreateInboxConversation404Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInboxConversation404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableCreateInboxConversation404Response struct {
	value *CreateInboxConversation404Response
	isSet bool
}

func (v NullableCreateInboxConversation404Response) Get() *CreateInboxConversation404Response {
	return v.value
}

func (v *NullableCreateInboxConversation404Response) Set(val *CreateInboxConversation404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInboxConversation404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInboxConversation404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInboxConversation404Response(val *CreateInboxConversation404Response) *NullableCreateInboxConversation404Response {
	return &NullableCreateInboxConversation404Response{value: val, isSet: true}
}

func (v NullableCreateInboxConversation404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInboxConversation404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
