/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the LikePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LikePost200Response{}

// LikePost200Response struct for LikePost200Response
type LikePost200Response struct {
	Status *string `json:"status,omitempty"`
	// The resolved native post ID
	PostId   *string `json:"postId,omitempty"`
	Platform *string `json:"platform,omitempty"`
	Liked    *bool   `json:"liked,omitempty"`
	// (Bluesky only) URI to use for unliking
	LikeUri *string `json:"likeUri,omitempty"`
}

// NewLikePost200Response instantiates a new LikePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLikePost200Response() *LikePost200Response {
	this := LikePost200Response{}
	return &this
}

// NewLikePost200ResponseWithDefaults instantiates a new LikePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLikePost200ResponseWithDefaults() *LikePost200Response {
	this := LikePost200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LikePost200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikePost200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LikePost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LikePost200Response) SetStatus(v string) {
	o.Status = &v
}

// GetPostId returns the PostId field value if set, zero value otherwise.
func (o *LikePost200Response) GetPostId() string {
	if o == nil || IsNil(o.PostId) {
		var ret string
		return ret
	}
	return *o.PostId
}

// GetPostIdOk returns a tuple with the PostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikePost200Response) GetPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.PostId) {
		return nil, false
	}
	return o.PostId, true
}

// HasPostId returns a boolean if a field has been set.
func (o *LikePost200Response) HasPostId() bool {
	if o != nil && !IsNil(o.PostId) {
		return true
	}

	return false
}

// SetPostId gets a reference to the given string and assigns it to the PostId field.
func (o *LikePost200Response) SetPostId(v string) {
	o.PostId = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *LikePost200Response) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikePost200Response) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *LikePost200Response) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *LikePost200Response) SetPlatform(v string) {
	o.Platform = &v
}

// GetLiked returns the Liked field value if set, zero value otherwise.
func (o *LikePost200Response) GetLiked() bool {
	if o == nil || IsNil(o.Liked) {
		var ret bool
		return ret
	}
	return *o.Liked
}

// GetLikedOk returns a tuple with the Liked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikePost200Response) GetLikedOk() (*bool, bool) {
	if o == nil || IsNil(o.Liked) {
		return nil, false
	}
	return o.Liked, true
}

// HasLiked returns a boolean if a field has been set.
func (o *LikePost200Response) HasLiked() bool {
	if o != nil && !IsNil(o.Liked) {
		return true
	}

	return false
}

// SetLiked gets a reference to the given bool and assigns it to the Liked field.
func (o *LikePost200Response) SetLiked(v bool) {
	o.Liked = &v
}

// GetLikeUri returns the LikeUri field value if set, zero value otherwise.
func (o *LikePost200Response) GetLikeUri() string {
	if o == nil || IsNil(o.LikeUri) {
		var ret string
		return ret
	}
	return *o.LikeUri
}

// GetLikeUriOk returns a tuple with the LikeUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikePost200Response) GetLikeUriOk() (*string, bool) {
	if o == nil || IsNil(o.LikeUri) {
		return nil, false
	}
	return o.LikeUri, true
}

// HasLikeUri returns a boolean if a field has been set.
func (o *LikePost200Response) HasLikeUri() bool {
	if o != nil && !IsNil(o.LikeUri) {
		return true
	}

	return false
}

// SetLikeUri gets a reference to the given string and assigns it to the LikeUri field.
func (o *LikePost200Response) SetLikeUri(v string) {
	o.LikeUri = &v
}

func (o LikePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LikePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PostId) {
		toSerialize["postId"] = o.PostId
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.Liked) {
		toSerialize["liked"] = o.Liked
	}
	if !IsNil(o.LikeUri) {
		toSerialize["likeUri"] = o.LikeUri
	}
	return toSerialize, nil
}

type NullableLikePost200Response struct {
	value *LikePost200Response
	isSet bool
}

func (v NullableLikePost200Response) Get() *LikePost200Response {
	return v.value
}

func (v *NullableLikePost200Response) Set(val *LikePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLikePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLikePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLikePost200Response(val *LikePost200Response) *NullableLikePost200Response {
	return &NullableLikePost200Response{value: val, isSet: true}
}

func (v NullableLikePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLikePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
