/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the ListAdKeywords200ResponseKeywordsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAdKeywords200ResponseKeywordsInner{}

// ListAdKeywords200ResponseKeywordsInner struct for ListAdKeywords200ResponseKeywordsInner
type ListAdKeywords200ResponseKeywordsInner struct {
	Id *string `json:"id,omitempty"`
	// Social account ID owning the sync
	AccountId *string `json:"accountId,omitempty"`
	ProfileId *string `json:"profileId,omitempty"`
	Platform  *string `json:"platform,omitempty"`
	// Google customer ID
	AdAccountId    *string        `json:"adAccountId,omitempty"`
	CampaignId     *string        `json:"campaignId,omitempty"`
	CampaignName   NullableString `json:"campaignName,omitempty"`
	CampaignStatus NullableString `json:"campaignStatus,omitempty"`
	// Google ad group ID
	AdSetId     *string        `json:"adSetId,omitempty"`
	AdSetName   NullableString `json:"adSetName,omitempty"`
	AdSetStatus NullableString `json:"adSetStatus,omitempty"`
	Keyword     *string        `json:"keyword,omitempty"`
	MatchType   *string        `json:"matchType,omitempty"`
	Status      *string        `json:"status,omitempty"`
	Negative    *bool          `json:"negative,omitempty"`
	SyncedAt    NullableTime   `json:"syncedAt,omitempty"`
}

// NewListAdKeywords200ResponseKeywordsInner instantiates a new ListAdKeywords200ResponseKeywordsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAdKeywords200ResponseKeywordsInner() *ListAdKeywords200ResponseKeywordsInner {
	this := ListAdKeywords200ResponseKeywordsInner{}
	return &this
}

// NewListAdKeywords200ResponseKeywordsInnerWithDefaults instantiates a new ListAdKeywords200ResponseKeywordsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAdKeywords200ResponseKeywordsInnerWithDefaults() *ListAdKeywords200ResponseKeywordsInner {
	this := ListAdKeywords200ResponseKeywordsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetId(v string) {
	o.Id = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetAccountId(v string) {
	o.AccountId = &v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId) {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetProfileId(v string) {
	o.ProfileId = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetPlatform(v string) {
	o.Platform = &v
}

// GetAdAccountId returns the AdAccountId field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdAccountId() string {
	if o == nil || IsNil(o.AdAccountId) {
		var ret string
		return ret
	}
	return *o.AdAccountId
}

// GetAdAccountIdOk returns a tuple with the AdAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AdAccountId) {
		return nil, false
	}
	return o.AdAccountId, true
}

// HasAdAccountId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasAdAccountId() bool {
	if o != nil && !IsNil(o.AdAccountId) {
		return true
	}

	return false
}

// SetAdAccountId gets a reference to the given string and assigns it to the AdAccountId field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdAccountId(v string) {
	o.AdAccountId = &v
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignId() string {
	if o == nil || IsNil(o.CampaignId) {
		var ret string
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignIdOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignId) {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasCampaignId() bool {
	if o != nil && !IsNil(o.CampaignId) {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetCampaignId(v string) {
	o.CampaignId = &v
}

// GetCampaignName returns the CampaignName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignName() string {
	if o == nil || IsNil(o.CampaignName.Get()) {
		var ret string
		return ret
	}
	return *o.CampaignName.Get()
}

// GetCampaignNameOk returns a tuple with the CampaignName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CampaignName.Get(), o.CampaignName.IsSet()
}

// HasCampaignName returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasCampaignName() bool {
	if o != nil && o.CampaignName.IsSet() {
		return true
	}

	return false
}

// SetCampaignName gets a reference to the given NullableString and assigns it to the CampaignName field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetCampaignName(v string) {
	o.CampaignName.Set(&v)
}

// SetCampaignNameNil sets the value for CampaignName to be an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) SetCampaignNameNil() {
	o.CampaignName.Set(nil)
}

// UnsetCampaignName ensures that no value is present for CampaignName, not even an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) UnsetCampaignName() {
	o.CampaignName.Unset()
}

// GetCampaignStatus returns the CampaignStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignStatus() string {
	if o == nil || IsNil(o.CampaignStatus.Get()) {
		var ret string
		return ret
	}
	return *o.CampaignStatus.Get()
}

// GetCampaignStatusOk returns a tuple with the CampaignStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAdKeywords200ResponseKeywordsInner) GetCampaignStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CampaignStatus.Get(), o.CampaignStatus.IsSet()
}

// HasCampaignStatus returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasCampaignStatus() bool {
	if o != nil && o.CampaignStatus.IsSet() {
		return true
	}

	return false
}

// SetCampaignStatus gets a reference to the given NullableString and assigns it to the CampaignStatus field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetCampaignStatus(v string) {
	o.CampaignStatus.Set(&v)
}

// SetCampaignStatusNil sets the value for CampaignStatus to be an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) SetCampaignStatusNil() {
	o.CampaignStatus.Set(nil)
}

// UnsetCampaignStatus ensures that no value is present for CampaignStatus, not even an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) UnsetCampaignStatus() {
	o.CampaignStatus.Unset()
}

// GetAdSetId returns the AdSetId field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetId() string {
	if o == nil || IsNil(o.AdSetId) {
		var ret string
		return ret
	}
	return *o.AdSetId
}

// GetAdSetIdOk returns a tuple with the AdSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AdSetId) {
		return nil, false
	}
	return o.AdSetId, true
}

// HasAdSetId returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasAdSetId() bool {
	if o != nil && !IsNil(o.AdSetId) {
		return true
	}

	return false
}

// SetAdSetId gets a reference to the given string and assigns it to the AdSetId field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdSetId(v string) {
	o.AdSetId = &v
}

// GetAdSetName returns the AdSetName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetName() string {
	if o == nil || IsNil(o.AdSetName.Get()) {
		var ret string
		return ret
	}
	return *o.AdSetName.Get()
}

// GetAdSetNameOk returns a tuple with the AdSetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdSetName.Get(), o.AdSetName.IsSet()
}

// HasAdSetName returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasAdSetName() bool {
	if o != nil && o.AdSetName.IsSet() {
		return true
	}

	return false
}

// SetAdSetName gets a reference to the given NullableString and assigns it to the AdSetName field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdSetName(v string) {
	o.AdSetName.Set(&v)
}

// SetAdSetNameNil sets the value for AdSetName to be an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdSetNameNil() {
	o.AdSetName.Set(nil)
}

// UnsetAdSetName ensures that no value is present for AdSetName, not even an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) UnsetAdSetName() {
	o.AdSetName.Unset()
}

// GetAdSetStatus returns the AdSetStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetStatus() string {
	if o == nil || IsNil(o.AdSetStatus.Get()) {
		var ret string
		return ret
	}
	return *o.AdSetStatus.Get()
}

// GetAdSetStatusOk returns a tuple with the AdSetStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAdKeywords200ResponseKeywordsInner) GetAdSetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdSetStatus.Get(), o.AdSetStatus.IsSet()
}

// HasAdSetStatus returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasAdSetStatus() bool {
	if o != nil && o.AdSetStatus.IsSet() {
		return true
	}

	return false
}

// SetAdSetStatus gets a reference to the given NullableString and assigns it to the AdSetStatus field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdSetStatus(v string) {
	o.AdSetStatus.Set(&v)
}

// SetAdSetStatusNil sets the value for AdSetStatus to be an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) SetAdSetStatusNil() {
	o.AdSetStatus.Set(nil)
}

// UnsetAdSetStatus ensures that no value is present for AdSetStatus, not even an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) UnsetAdSetStatus() {
	o.AdSetStatus.Unset()
}

// GetKeyword returns the Keyword field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetKeyword() string {
	if o == nil || IsNil(o.Keyword) {
		var ret string
		return ret
	}
	return *o.Keyword
}

// GetKeywordOk returns a tuple with the Keyword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetKeywordOk() (*string, bool) {
	if o == nil || IsNil(o.Keyword) {
		return nil, false
	}
	return o.Keyword, true
}

// HasKeyword returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasKeyword() bool {
	if o != nil && !IsNil(o.Keyword) {
		return true
	}

	return false
}

// SetKeyword gets a reference to the given string and assigns it to the Keyword field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetKeyword(v string) {
	o.Keyword = &v
}

// GetMatchType returns the MatchType field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetMatchType() string {
	if o == nil || IsNil(o.MatchType) {
		var ret string
		return ret
	}
	return *o.MatchType
}

// GetMatchTypeOk returns a tuple with the MatchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetMatchTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MatchType) {
		return nil, false
	}
	return o.MatchType, true
}

// HasMatchType returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasMatchType() bool {
	if o != nil && !IsNil(o.MatchType) {
		return true
	}

	return false
}

// SetMatchType gets a reference to the given string and assigns it to the MatchType field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetMatchType(v string) {
	o.MatchType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetStatus(v string) {
	o.Status = &v
}

// GetNegative returns the Negative field value if set, zero value otherwise.
func (o *ListAdKeywords200ResponseKeywordsInner) GetNegative() bool {
	if o == nil || IsNil(o.Negative) {
		var ret bool
		return ret
	}
	return *o.Negative
}

// GetNegativeOk returns a tuple with the Negative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) GetNegativeOk() (*bool, bool) {
	if o == nil || IsNil(o.Negative) {
		return nil, false
	}
	return o.Negative, true
}

// HasNegative returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasNegative() bool {
	if o != nil && !IsNil(o.Negative) {
		return true
	}

	return false
}

// SetNegative gets a reference to the given bool and assigns it to the Negative field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetNegative(v bool) {
	o.Negative = &v
}

// GetSyncedAt returns the SyncedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAdKeywords200ResponseKeywordsInner) GetSyncedAt() time.Time {
	if o == nil || IsNil(o.SyncedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SyncedAt.Get()
}

// GetSyncedAtOk returns a tuple with the SyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAdKeywords200ResponseKeywordsInner) GetSyncedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SyncedAt.Get(), o.SyncedAt.IsSet()
}

// HasSyncedAt returns a boolean if a field has been set.
func (o *ListAdKeywords200ResponseKeywordsInner) HasSyncedAt() bool {
	if o != nil && o.SyncedAt.IsSet() {
		return true
	}

	return false
}

// SetSyncedAt gets a reference to the given NullableTime and assigns it to the SyncedAt field.
func (o *ListAdKeywords200ResponseKeywordsInner) SetSyncedAt(v time.Time) {
	o.SyncedAt.Set(&v)
}

// SetSyncedAtNil sets the value for SyncedAt to be an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) SetSyncedAtNil() {
	o.SyncedAt.Set(nil)
}

// UnsetSyncedAt ensures that no value is present for SyncedAt, not even an explicit nil
func (o *ListAdKeywords200ResponseKeywordsInner) UnsetSyncedAt() {
	o.SyncedAt.Unset()
}

func (o ListAdKeywords200ResponseKeywordsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAdKeywords200ResponseKeywordsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.ProfileId) {
		toSerialize["profileId"] = o.ProfileId
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.AdAccountId) {
		toSerialize["adAccountId"] = o.AdAccountId
	}
	if !IsNil(o.CampaignId) {
		toSerialize["campaignId"] = o.CampaignId
	}
	if o.CampaignName.IsSet() {
		toSerialize["campaignName"] = o.CampaignName.Get()
	}
	if o.CampaignStatus.IsSet() {
		toSerialize["campaignStatus"] = o.CampaignStatus.Get()
	}
	if !IsNil(o.AdSetId) {
		toSerialize["adSetId"] = o.AdSetId
	}
	if o.AdSetName.IsSet() {
		toSerialize["adSetName"] = o.AdSetName.Get()
	}
	if o.AdSetStatus.IsSet() {
		toSerialize["adSetStatus"] = o.AdSetStatus.Get()
	}
	if !IsNil(o.Keyword) {
		toSerialize["keyword"] = o.Keyword
	}
	if !IsNil(o.MatchType) {
		toSerialize["matchType"] = o.MatchType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Negative) {
		toSerialize["negative"] = o.Negative
	}
	if o.SyncedAt.IsSet() {
		toSerialize["syncedAt"] = o.SyncedAt.Get()
	}
	return toSerialize, nil
}

type NullableListAdKeywords200ResponseKeywordsInner struct {
	value *ListAdKeywords200ResponseKeywordsInner
	isSet bool
}

func (v NullableListAdKeywords200ResponseKeywordsInner) Get() *ListAdKeywords200ResponseKeywordsInner {
	return v.value
}

func (v *NullableListAdKeywords200ResponseKeywordsInner) Set(val *ListAdKeywords200ResponseKeywordsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListAdKeywords200ResponseKeywordsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListAdKeywords200ResponseKeywordsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAdKeywords200ResponseKeywordsInner(val *ListAdKeywords200ResponseKeywordsInner) *NullableListAdKeywords200ResponseKeywordsInner {
	return &NullableListAdKeywords200ResponseKeywordsInner{value: val, isSet: true}
}

func (v NullableListAdKeywords200ResponseKeywordsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAdKeywords200ResponseKeywordsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
