/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the UpdateCommentAutomationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCommentAutomationRequest{}

// UpdateCommentAutomationRequest struct for UpdateCommentAutomationRequest
type UpdateCommentAutomationRequest struct {
	Name *string `json:"name,omitempty"`
	// What fires the automation. Changing it detaches the automation from its bound post or story (a post id and a story id are different objects), unless this same request sets a new binding. 'story_reply' is Instagram only.
	Trigger  *string  `json:"trigger,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	// How a keyword is compared with the comment. 'contains' (default) matches anywhere, even inside another word (keyword 'app' fires on 'happy'). 'word' matches the keyword only as a standalone word. 'exact' requires the whole comment to be exactly the keyword.
	MatchMode *string `json:"matchMode,omitempty"`
	// Comments containing one of these never trigger the automation, even when a trigger keyword also matches. Compared using the same matchMode.
	ExcludeKeywords []string `json:"excludeKeywords,omitempty"`
	// Only with matchMode=word: also fire on close misspellings of a keyword (one edit for 4-7 character keywords, two from 8 up). Keywords shorter than 4 characters are never fuzzy-matched.
	TypoTolerance *bool   `json:"typoTolerance,omitempty"`
	DmMessage     *string `json:"dmMessage,omitempty"`
	// Inline DM buttons (1-3). Pass [] to clear all buttons.
	Buttons      []DmButton `json:"buttons,omitempty"`
	CommentReply *string    `json:"commentReply,omitempty"`
	// Alternate DM texts for random rotation (see create). Pass [] to clear.
	DmMessageVariations []string `json:"dmMessageVariations,omitempty"`
	// Alternate public replies for random rotation. Pass [] to clear.
	CommentReplyVariations []string `json:"commentReplyVariations,omitempty"`
	// Wrap link buttons in a tracked redirect to count clicks. Pass false to send links untouched.
	LinkTracking *bool `json:"linkTracking,omitempty"`
	// Tag applied to a contact when they click a tracked link (requires linkTracking). Empty string clears it.
	ClickTag   *string                      `json:"clickTag,omitempty"`
	Audience   *CommentAutomationAudience   `json:"audience,omitempty"`
	FollowGate *CommentAutomationFollowGate `json:"followGate,omitempty"`
	IsActive   *bool                        `json:"isActive,omitempty"`
}

// NewUpdateCommentAutomationRequest instantiates a new UpdateCommentAutomationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCommentAutomationRequest() *UpdateCommentAutomationRequest {
	this := UpdateCommentAutomationRequest{}
	return &this
}

// NewUpdateCommentAutomationRequestWithDefaults instantiates a new UpdateCommentAutomationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCommentAutomationRequestWithDefaults() *UpdateCommentAutomationRequest {
	this := UpdateCommentAutomationRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCommentAutomationRequest) SetName(v string) {
	o.Name = &v
}

// GetTrigger returns the Trigger field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetTrigger() string {
	if o == nil || IsNil(o.Trigger) {
		var ret string
		return ret
	}
	return *o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetTriggerOk() (*string, bool) {
	if o == nil || IsNil(o.Trigger) {
		return nil, false
	}
	return o.Trigger, true
}

// HasTrigger returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasTrigger() bool {
	if o != nil && !IsNil(o.Trigger) {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given string and assigns it to the Trigger field.
func (o *UpdateCommentAutomationRequest) SetTrigger(v string) {
	o.Trigger = &v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *UpdateCommentAutomationRequest) SetKeywords(v []string) {
	o.Keywords = v
}

// GetMatchMode returns the MatchMode field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetMatchMode() string {
	if o == nil || IsNil(o.MatchMode) {
		var ret string
		return ret
	}
	return *o.MatchMode
}

// GetMatchModeOk returns a tuple with the MatchMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetMatchModeOk() (*string, bool) {
	if o == nil || IsNil(o.MatchMode) {
		return nil, false
	}
	return o.MatchMode, true
}

// HasMatchMode returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasMatchMode() bool {
	if o != nil && !IsNil(o.MatchMode) {
		return true
	}

	return false
}

// SetMatchMode gets a reference to the given string and assigns it to the MatchMode field.
func (o *UpdateCommentAutomationRequest) SetMatchMode(v string) {
	o.MatchMode = &v
}

// GetExcludeKeywords returns the ExcludeKeywords field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetExcludeKeywords() []string {
	if o == nil || IsNil(o.ExcludeKeywords) {
		var ret []string
		return ret
	}
	return o.ExcludeKeywords
}

// GetExcludeKeywordsOk returns a tuple with the ExcludeKeywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetExcludeKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeKeywords) {
		return nil, false
	}
	return o.ExcludeKeywords, true
}

// HasExcludeKeywords returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasExcludeKeywords() bool {
	if o != nil && !IsNil(o.ExcludeKeywords) {
		return true
	}

	return false
}

// SetExcludeKeywords gets a reference to the given []string and assigns it to the ExcludeKeywords field.
func (o *UpdateCommentAutomationRequest) SetExcludeKeywords(v []string) {
	o.ExcludeKeywords = v
}

// GetTypoTolerance returns the TypoTolerance field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetTypoTolerance() bool {
	if o == nil || IsNil(o.TypoTolerance) {
		var ret bool
		return ret
	}
	return *o.TypoTolerance
}

// GetTypoToleranceOk returns a tuple with the TypoTolerance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetTypoToleranceOk() (*bool, bool) {
	if o == nil || IsNil(o.TypoTolerance) {
		return nil, false
	}
	return o.TypoTolerance, true
}

// HasTypoTolerance returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasTypoTolerance() bool {
	if o != nil && !IsNil(o.TypoTolerance) {
		return true
	}

	return false
}

// SetTypoTolerance gets a reference to the given bool and assigns it to the TypoTolerance field.
func (o *UpdateCommentAutomationRequest) SetTypoTolerance(v bool) {
	o.TypoTolerance = &v
}

// GetDmMessage returns the DmMessage field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetDmMessage() string {
	if o == nil || IsNil(o.DmMessage) {
		var ret string
		return ret
	}
	return *o.DmMessage
}

// GetDmMessageOk returns a tuple with the DmMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetDmMessageOk() (*string, bool) {
	if o == nil || IsNil(o.DmMessage) {
		return nil, false
	}
	return o.DmMessage, true
}

// HasDmMessage returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasDmMessage() bool {
	if o != nil && !IsNil(o.DmMessage) {
		return true
	}

	return false
}

// SetDmMessage gets a reference to the given string and assigns it to the DmMessage field.
func (o *UpdateCommentAutomationRequest) SetDmMessage(v string) {
	o.DmMessage = &v
}

// GetButtons returns the Buttons field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetButtons() []DmButton {
	if o == nil || IsNil(o.Buttons) {
		var ret []DmButton
		return ret
	}
	return o.Buttons
}

// GetButtonsOk returns a tuple with the Buttons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetButtonsOk() ([]DmButton, bool) {
	if o == nil || IsNil(o.Buttons) {
		return nil, false
	}
	return o.Buttons, true
}

// HasButtons returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasButtons() bool {
	if o != nil && !IsNil(o.Buttons) {
		return true
	}

	return false
}

// SetButtons gets a reference to the given []DmButton and assigns it to the Buttons field.
func (o *UpdateCommentAutomationRequest) SetButtons(v []DmButton) {
	o.Buttons = v
}

// GetCommentReply returns the CommentReply field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetCommentReply() string {
	if o == nil || IsNil(o.CommentReply) {
		var ret string
		return ret
	}
	return *o.CommentReply
}

// GetCommentReplyOk returns a tuple with the CommentReply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetCommentReplyOk() (*string, bool) {
	if o == nil || IsNil(o.CommentReply) {
		return nil, false
	}
	return o.CommentReply, true
}

// HasCommentReply returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasCommentReply() bool {
	if o != nil && !IsNil(o.CommentReply) {
		return true
	}

	return false
}

// SetCommentReply gets a reference to the given string and assigns it to the CommentReply field.
func (o *UpdateCommentAutomationRequest) SetCommentReply(v string) {
	o.CommentReply = &v
}

// GetDmMessageVariations returns the DmMessageVariations field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetDmMessageVariations() []string {
	if o == nil || IsNil(o.DmMessageVariations) {
		var ret []string
		return ret
	}
	return o.DmMessageVariations
}

// GetDmMessageVariationsOk returns a tuple with the DmMessageVariations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetDmMessageVariationsOk() ([]string, bool) {
	if o == nil || IsNil(o.DmMessageVariations) {
		return nil, false
	}
	return o.DmMessageVariations, true
}

// HasDmMessageVariations returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasDmMessageVariations() bool {
	if o != nil && !IsNil(o.DmMessageVariations) {
		return true
	}

	return false
}

// SetDmMessageVariations gets a reference to the given []string and assigns it to the DmMessageVariations field.
func (o *UpdateCommentAutomationRequest) SetDmMessageVariations(v []string) {
	o.DmMessageVariations = v
}

// GetCommentReplyVariations returns the CommentReplyVariations field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetCommentReplyVariations() []string {
	if o == nil || IsNil(o.CommentReplyVariations) {
		var ret []string
		return ret
	}
	return o.CommentReplyVariations
}

// GetCommentReplyVariationsOk returns a tuple with the CommentReplyVariations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetCommentReplyVariationsOk() ([]string, bool) {
	if o == nil || IsNil(o.CommentReplyVariations) {
		return nil, false
	}
	return o.CommentReplyVariations, true
}

// HasCommentReplyVariations returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasCommentReplyVariations() bool {
	if o != nil && !IsNil(o.CommentReplyVariations) {
		return true
	}

	return false
}

// SetCommentReplyVariations gets a reference to the given []string and assigns it to the CommentReplyVariations field.
func (o *UpdateCommentAutomationRequest) SetCommentReplyVariations(v []string) {
	o.CommentReplyVariations = v
}

// GetLinkTracking returns the LinkTracking field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetLinkTracking() bool {
	if o == nil || IsNil(o.LinkTracking) {
		var ret bool
		return ret
	}
	return *o.LinkTracking
}

// GetLinkTrackingOk returns a tuple with the LinkTracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetLinkTrackingOk() (*bool, bool) {
	if o == nil || IsNil(o.LinkTracking) {
		return nil, false
	}
	return o.LinkTracking, true
}

// HasLinkTracking returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasLinkTracking() bool {
	if o != nil && !IsNil(o.LinkTracking) {
		return true
	}

	return false
}

// SetLinkTracking gets a reference to the given bool and assigns it to the LinkTracking field.
func (o *UpdateCommentAutomationRequest) SetLinkTracking(v bool) {
	o.LinkTracking = &v
}

// GetClickTag returns the ClickTag field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetClickTag() string {
	if o == nil || IsNil(o.ClickTag) {
		var ret string
		return ret
	}
	return *o.ClickTag
}

// GetClickTagOk returns a tuple with the ClickTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetClickTagOk() (*string, bool) {
	if o == nil || IsNil(o.ClickTag) {
		return nil, false
	}
	return o.ClickTag, true
}

// HasClickTag returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasClickTag() bool {
	if o != nil && !IsNil(o.ClickTag) {
		return true
	}

	return false
}

// SetClickTag gets a reference to the given string and assigns it to the ClickTag field.
func (o *UpdateCommentAutomationRequest) SetClickTag(v string) {
	o.ClickTag = &v
}

// GetAudience returns the Audience field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetAudience() CommentAutomationAudience {
	if o == nil || IsNil(o.Audience) {
		var ret CommentAutomationAudience
		return ret
	}
	return *o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetAudienceOk() (*CommentAutomationAudience, bool) {
	if o == nil || IsNil(o.Audience) {
		return nil, false
	}
	return o.Audience, true
}

// HasAudience returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasAudience() bool {
	if o != nil && !IsNil(o.Audience) {
		return true
	}

	return false
}

// SetAudience gets a reference to the given CommentAutomationAudience and assigns it to the Audience field.
func (o *UpdateCommentAutomationRequest) SetAudience(v CommentAutomationAudience) {
	o.Audience = &v
}

// GetFollowGate returns the FollowGate field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetFollowGate() CommentAutomationFollowGate {
	if o == nil || IsNil(o.FollowGate) {
		var ret CommentAutomationFollowGate
		return ret
	}
	return *o.FollowGate
}

// GetFollowGateOk returns a tuple with the FollowGate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetFollowGateOk() (*CommentAutomationFollowGate, bool) {
	if o == nil || IsNil(o.FollowGate) {
		return nil, false
	}
	return o.FollowGate, true
}

// HasFollowGate returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasFollowGate() bool {
	if o != nil && !IsNil(o.FollowGate) {
		return true
	}

	return false
}

// SetFollowGate gets a reference to the given CommentAutomationFollowGate and assigns it to the FollowGate field.
func (o *UpdateCommentAutomationRequest) SetFollowGate(v CommentAutomationFollowGate) {
	o.FollowGate = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *UpdateCommentAutomationRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentAutomationRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *UpdateCommentAutomationRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *UpdateCommentAutomationRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o UpdateCommentAutomationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCommentAutomationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Trigger) {
		toSerialize["trigger"] = o.Trigger
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.MatchMode) {
		toSerialize["matchMode"] = o.MatchMode
	}
	if !IsNil(o.ExcludeKeywords) {
		toSerialize["excludeKeywords"] = o.ExcludeKeywords
	}
	if !IsNil(o.TypoTolerance) {
		toSerialize["typoTolerance"] = o.TypoTolerance
	}
	if !IsNil(o.DmMessage) {
		toSerialize["dmMessage"] = o.DmMessage
	}
	if !IsNil(o.Buttons) {
		toSerialize["buttons"] = o.Buttons
	}
	if !IsNil(o.CommentReply) {
		toSerialize["commentReply"] = o.CommentReply
	}
	if !IsNil(o.DmMessageVariations) {
		toSerialize["dmMessageVariations"] = o.DmMessageVariations
	}
	if !IsNil(o.CommentReplyVariations) {
		toSerialize["commentReplyVariations"] = o.CommentReplyVariations
	}
	if !IsNil(o.LinkTracking) {
		toSerialize["linkTracking"] = o.LinkTracking
	}
	if !IsNil(o.ClickTag) {
		toSerialize["clickTag"] = o.ClickTag
	}
	if !IsNil(o.Audience) {
		toSerialize["audience"] = o.Audience
	}
	if !IsNil(o.FollowGate) {
		toSerialize["followGate"] = o.FollowGate
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableUpdateCommentAutomationRequest struct {
	value *UpdateCommentAutomationRequest
	isSet bool
}

func (v NullableUpdateCommentAutomationRequest) Get() *UpdateCommentAutomationRequest {
	return v.value
}

func (v *NullableUpdateCommentAutomationRequest) Set(val *UpdateCommentAutomationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCommentAutomationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCommentAutomationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCommentAutomationRequest(val *UpdateCommentAutomationRequest) *NullableUpdateCommentAutomationRequest {
	return &NullableUpdateCommentAutomationRequest{value: val, isSet: true}
}

func (v NullableUpdateCommentAutomationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCommentAutomationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
