/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AttachCampaignAssetsRequestSitelinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachCampaignAssetsRequestSitelinksInner{}

// AttachCampaignAssetsRequestSitelinksInner struct for AttachCampaignAssetsRequestSitelinksInner
type AttachCampaignAssetsRequestSitelinksInner struct {
	Text         string  `json:"text"`
	LinkUrl      string  `json:"linkUrl"`
	Description1 *string `json:"description1,omitempty"`
	Description2 *string `json:"description2,omitempty"`
}

type _AttachCampaignAssetsRequestSitelinksInner AttachCampaignAssetsRequestSitelinksInner

// NewAttachCampaignAssetsRequestSitelinksInner instantiates a new AttachCampaignAssetsRequestSitelinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachCampaignAssetsRequestSitelinksInner(text string, linkUrl string) *AttachCampaignAssetsRequestSitelinksInner {
	this := AttachCampaignAssetsRequestSitelinksInner{}
	this.Text = text
	this.LinkUrl = linkUrl
	return &this
}

// NewAttachCampaignAssetsRequestSitelinksInnerWithDefaults instantiates a new AttachCampaignAssetsRequestSitelinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachCampaignAssetsRequestSitelinksInnerWithDefaults() *AttachCampaignAssetsRequestSitelinksInner {
	this := AttachCampaignAssetsRequestSitelinksInner{}
	return &this
}

// GetText returns the Text field value
func (o *AttachCampaignAssetsRequestSitelinksInner) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *AttachCampaignAssetsRequestSitelinksInner) SetText(v string) {
	o.Text = v
}

// GetLinkUrl returns the LinkUrl field value
func (o *AttachCampaignAssetsRequestSitelinksInner) GetLinkUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkUrl
}

// GetLinkUrlOk returns a tuple with the LinkUrl field value
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetLinkUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkUrl, true
}

// SetLinkUrl sets field value
func (o *AttachCampaignAssetsRequestSitelinksInner) SetLinkUrl(v string) {
	o.LinkUrl = v
}

// GetDescription1 returns the Description1 field value if set, zero value otherwise.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetDescription1() string {
	if o == nil || IsNil(o.Description1) {
		var ret string
		return ret
	}
	return *o.Description1
}

// GetDescription1Ok returns a tuple with the Description1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetDescription1Ok() (*string, bool) {
	if o == nil || IsNil(o.Description1) {
		return nil, false
	}
	return o.Description1, true
}

// HasDescription1 returns a boolean if a field has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) HasDescription1() bool {
	if o != nil && !IsNil(o.Description1) {
		return true
	}

	return false
}

// SetDescription1 gets a reference to the given string and assigns it to the Description1 field.
func (o *AttachCampaignAssetsRequestSitelinksInner) SetDescription1(v string) {
	o.Description1 = &v
}

// GetDescription2 returns the Description2 field value if set, zero value otherwise.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetDescription2() string {
	if o == nil || IsNil(o.Description2) {
		var ret string
		return ret
	}
	return *o.Description2
}

// GetDescription2Ok returns a tuple with the Description2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) GetDescription2Ok() (*string, bool) {
	if o == nil || IsNil(o.Description2) {
		return nil, false
	}
	return o.Description2, true
}

// HasDescription2 returns a boolean if a field has been set.
func (o *AttachCampaignAssetsRequestSitelinksInner) HasDescription2() bool {
	if o != nil && !IsNil(o.Description2) {
		return true
	}

	return false
}

// SetDescription2 gets a reference to the given string and assigns it to the Description2 field.
func (o *AttachCampaignAssetsRequestSitelinksInner) SetDescription2(v string) {
	o.Description2 = &v
}

func (o AttachCampaignAssetsRequestSitelinksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachCampaignAssetsRequestSitelinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["linkUrl"] = o.LinkUrl
	if !IsNil(o.Description1) {
		toSerialize["description1"] = o.Description1
	}
	if !IsNil(o.Description2) {
		toSerialize["description2"] = o.Description2
	}
	return toSerialize, nil
}

func (o *AttachCampaignAssetsRequestSitelinksInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"linkUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachCampaignAssetsRequestSitelinksInner := _AttachCampaignAssetsRequestSitelinksInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachCampaignAssetsRequestSitelinksInner)

	if err != nil {
		return err
	}

	*o = AttachCampaignAssetsRequestSitelinksInner(varAttachCampaignAssetsRequestSitelinksInner)

	return err
}

type NullableAttachCampaignAssetsRequestSitelinksInner struct {
	value *AttachCampaignAssetsRequestSitelinksInner
	isSet bool
}

func (v NullableAttachCampaignAssetsRequestSitelinksInner) Get() *AttachCampaignAssetsRequestSitelinksInner {
	return v.value
}

func (v *NullableAttachCampaignAssetsRequestSitelinksInner) Set(val *AttachCampaignAssetsRequestSitelinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachCampaignAssetsRequestSitelinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachCampaignAssetsRequestSitelinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachCampaignAssetsRequestSitelinksInner(val *AttachCampaignAssetsRequestSitelinksInner) *NullableAttachCampaignAssetsRequestSitelinksInner {
	return &NullableAttachCampaignAssetsRequestSitelinksInner{value: val, isSet: true}
}

func (v NullableAttachCampaignAssetsRequestSitelinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachCampaignAssetsRequestSitelinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
