/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the MetaAdsPlatformData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaAdsPlatformData{}

// MetaAdsPlatformData Meta (facebook/instagram) options for platformSpecificData on POST /v1/ads/boost and /v1/ads/create. Unknown keys are rejected, not dropped.
type MetaAdsPlatformData struct {
	BidStrategy *BidStrategy `json:"bidStrategy,omitempty"`
	// Whole currency units (USD: 5 = $5.00). Required when bidStrategy is LOWEST_COST_WITH_BID_CAP or COST_CAP.
	BidAmount *float32 `json:"bidAmount,omitempty"`
	// Decimal ROAS multiplier (2.0 = 2.0x). Required when bidStrategy is LOWEST_COST_WITH_MIN_ROAS.
	RoasAverageFloor *float32 `json:"roasAverageFloor,omitempty"`
}

// NewMetaAdsPlatformData instantiates a new MetaAdsPlatformData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaAdsPlatformData() *MetaAdsPlatformData {
	this := MetaAdsPlatformData{}
	return &this
}

// NewMetaAdsPlatformDataWithDefaults instantiates a new MetaAdsPlatformData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaAdsPlatformDataWithDefaults() *MetaAdsPlatformData {
	this := MetaAdsPlatformData{}
	return &this
}

// GetBidStrategy returns the BidStrategy field value if set, zero value otherwise.
func (o *MetaAdsPlatformData) GetBidStrategy() BidStrategy {
	if o == nil || IsNil(o.BidStrategy) {
		var ret BidStrategy
		return ret
	}
	return *o.BidStrategy
}

// GetBidStrategyOk returns a tuple with the BidStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAdsPlatformData) GetBidStrategyOk() (*BidStrategy, bool) {
	if o == nil || IsNil(o.BidStrategy) {
		return nil, false
	}
	return o.BidStrategy, true
}

// HasBidStrategy returns a boolean if a field has been set.
func (o *MetaAdsPlatformData) HasBidStrategy() bool {
	if o != nil && !IsNil(o.BidStrategy) {
		return true
	}

	return false
}

// SetBidStrategy gets a reference to the given BidStrategy and assigns it to the BidStrategy field.
func (o *MetaAdsPlatformData) SetBidStrategy(v BidStrategy) {
	o.BidStrategy = &v
}

// GetBidAmount returns the BidAmount field value if set, zero value otherwise.
func (o *MetaAdsPlatformData) GetBidAmount() float32 {
	if o == nil || IsNil(o.BidAmount) {
		var ret float32
		return ret
	}
	return *o.BidAmount
}

// GetBidAmountOk returns a tuple with the BidAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAdsPlatformData) GetBidAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.BidAmount) {
		return nil, false
	}
	return o.BidAmount, true
}

// HasBidAmount returns a boolean if a field has been set.
func (o *MetaAdsPlatformData) HasBidAmount() bool {
	if o != nil && !IsNil(o.BidAmount) {
		return true
	}

	return false
}

// SetBidAmount gets a reference to the given float32 and assigns it to the BidAmount field.
func (o *MetaAdsPlatformData) SetBidAmount(v float32) {
	o.BidAmount = &v
}

// GetRoasAverageFloor returns the RoasAverageFloor field value if set, zero value otherwise.
func (o *MetaAdsPlatformData) GetRoasAverageFloor() float32 {
	if o == nil || IsNil(o.RoasAverageFloor) {
		var ret float32
		return ret
	}
	return *o.RoasAverageFloor
}

// GetRoasAverageFloorOk returns a tuple with the RoasAverageFloor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAdsPlatformData) GetRoasAverageFloorOk() (*float32, bool) {
	if o == nil || IsNil(o.RoasAverageFloor) {
		return nil, false
	}
	return o.RoasAverageFloor, true
}

// HasRoasAverageFloor returns a boolean if a field has been set.
func (o *MetaAdsPlatformData) HasRoasAverageFloor() bool {
	if o != nil && !IsNil(o.RoasAverageFloor) {
		return true
	}

	return false
}

// SetRoasAverageFloor gets a reference to the given float32 and assigns it to the RoasAverageFloor field.
func (o *MetaAdsPlatformData) SetRoasAverageFloor(v float32) {
	o.RoasAverageFloor = &v
}

func (o MetaAdsPlatformData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaAdsPlatformData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BidStrategy) {
		toSerialize["bidStrategy"] = o.BidStrategy
	}
	if !IsNil(o.BidAmount) {
		toSerialize["bidAmount"] = o.BidAmount
	}
	if !IsNil(o.RoasAverageFloor) {
		toSerialize["roasAverageFloor"] = o.RoasAverageFloor
	}
	return toSerialize, nil
}

type NullableMetaAdsPlatformData struct {
	value *MetaAdsPlatformData
	isSet bool
}

func (v NullableMetaAdsPlatformData) Get() *MetaAdsPlatformData {
	return v.value
}

func (v *NullableMetaAdsPlatformData) Set(val *MetaAdsPlatformData) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaAdsPlatformData) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaAdsPlatformData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaAdsPlatformData(val *MetaAdsPlatformData) *NullableMetaAdsPlatformData {
	return &NullableMetaAdsPlatformData{value: val, isSet: true}
}

func (v NullableMetaAdsPlatformData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaAdsPlatformData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
