/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AttachCampaignAssetsRequestStructuredSnippetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachCampaignAssetsRequestStructuredSnippetsInner{}

// AttachCampaignAssetsRequestStructuredSnippetsInner struct for AttachCampaignAssetsRequestStructuredSnippetsInner
type AttachCampaignAssetsRequestStructuredSnippetsInner struct {
	Header string   `json:"header"`
	Values []string `json:"values"`
}

type _AttachCampaignAssetsRequestStructuredSnippetsInner AttachCampaignAssetsRequestStructuredSnippetsInner

// NewAttachCampaignAssetsRequestStructuredSnippetsInner instantiates a new AttachCampaignAssetsRequestStructuredSnippetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachCampaignAssetsRequestStructuredSnippetsInner(header string, values []string) *AttachCampaignAssetsRequestStructuredSnippetsInner {
	this := AttachCampaignAssetsRequestStructuredSnippetsInner{}
	this.Header = header
	this.Values = values
	return &this
}

// NewAttachCampaignAssetsRequestStructuredSnippetsInnerWithDefaults instantiates a new AttachCampaignAssetsRequestStructuredSnippetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachCampaignAssetsRequestStructuredSnippetsInnerWithDefaults() *AttachCampaignAssetsRequestStructuredSnippetsInner {
	this := AttachCampaignAssetsRequestStructuredSnippetsInner{}
	return &this
}

// GetHeader returns the Header field value
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) GetHeader() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Header
}

// GetHeaderOk returns a tuple with the Header field value
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) GetHeaderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Header, true
}

// SetHeader sets field value
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) SetHeader(v string) {
	o.Header = v
}

// GetValues returns the Values field value
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) GetValues() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) GetValuesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) SetValues(v []string) {
	o.Values = v
}

func (o AttachCampaignAssetsRequestStructuredSnippetsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachCampaignAssetsRequestStructuredSnippetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["header"] = o.Header
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *AttachCampaignAssetsRequestStructuredSnippetsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"header",
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachCampaignAssetsRequestStructuredSnippetsInner := _AttachCampaignAssetsRequestStructuredSnippetsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachCampaignAssetsRequestStructuredSnippetsInner)

	if err != nil {
		return err
	}

	*o = AttachCampaignAssetsRequestStructuredSnippetsInner(varAttachCampaignAssetsRequestStructuredSnippetsInner)

	return err
}

type NullableAttachCampaignAssetsRequestStructuredSnippetsInner struct {
	value *AttachCampaignAssetsRequestStructuredSnippetsInner
	isSet bool
}

func (v NullableAttachCampaignAssetsRequestStructuredSnippetsInner) Get() *AttachCampaignAssetsRequestStructuredSnippetsInner {
	return v.value
}

func (v *NullableAttachCampaignAssetsRequestStructuredSnippetsInner) Set(val *AttachCampaignAssetsRequestStructuredSnippetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachCampaignAssetsRequestStructuredSnippetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachCampaignAssetsRequestStructuredSnippetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachCampaignAssetsRequestStructuredSnippetsInner(val *AttachCampaignAssetsRequestStructuredSnippetsInner) *NullableAttachCampaignAssetsRequestStructuredSnippetsInner {
	return &NullableAttachCampaignAssetsRequestStructuredSnippetsInner{value: val, isSet: true}
}

func (v NullableAttachCampaignAssetsRequestStructuredSnippetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachCampaignAssetsRequestStructuredSnippetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
