/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the WebhookPayloadMessageSentMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPayloadMessageSentMetadata{}

// WebhookPayloadMessageSentMetadata Platform-specific context for the sent message. The key is present only when the send carried some context, and absent otherwise: it is never null and never an empty object.
type WebhookPayloadMessageSentMetadata struct {
	// platformMessageId of the message this send is a quote-reply to. Set when the reply was sent through Zernio with `replyTo` on the inbox send API (WhatsApp and Telegram), and when the operator replied from the native WhatsApp Business, Instagram or Messenger app. WhatsApp API sends carry it on the event fired from the delivery status, so it arrives on the same `message.sent` as any other WhatsApp send.
	QuotedMessageId *string `json:"quotedMessageId,omitempty"`
	// Slack only. Parent thread ts of the sent message. Pass it back as `replyTo` on the inbox send API to keep replying inside the thread.
	ThreadTs *string `json:"threadTs,omitempty"`
}

// NewWebhookPayloadMessageSentMetadata instantiates a new WebhookPayloadMessageSentMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPayloadMessageSentMetadata() *WebhookPayloadMessageSentMetadata {
	this := WebhookPayloadMessageSentMetadata{}
	return &this
}

// NewWebhookPayloadMessageSentMetadataWithDefaults instantiates a new WebhookPayloadMessageSentMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPayloadMessageSentMetadataWithDefaults() *WebhookPayloadMessageSentMetadata {
	this := WebhookPayloadMessageSentMetadata{}
	return &this
}

// GetQuotedMessageId returns the QuotedMessageId field value if set, zero value otherwise.
func (o *WebhookPayloadMessageSentMetadata) GetQuotedMessageId() string {
	if o == nil || IsNil(o.QuotedMessageId) {
		var ret string
		return ret
	}
	return *o.QuotedMessageId
}

// GetQuotedMessageIdOk returns a tuple with the QuotedMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayloadMessageSentMetadata) GetQuotedMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.QuotedMessageId) {
		return nil, false
	}
	return o.QuotedMessageId, true
}

// HasQuotedMessageId returns a boolean if a field has been set.
func (o *WebhookPayloadMessageSentMetadata) HasQuotedMessageId() bool {
	if o != nil && !IsNil(o.QuotedMessageId) {
		return true
	}

	return false
}

// SetQuotedMessageId gets a reference to the given string and assigns it to the QuotedMessageId field.
func (o *WebhookPayloadMessageSentMetadata) SetQuotedMessageId(v string) {
	o.QuotedMessageId = &v
}

// GetThreadTs returns the ThreadTs field value if set, zero value otherwise.
func (o *WebhookPayloadMessageSentMetadata) GetThreadTs() string {
	if o == nil || IsNil(o.ThreadTs) {
		var ret string
		return ret
	}
	return *o.ThreadTs
}

// GetThreadTsOk returns a tuple with the ThreadTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayloadMessageSentMetadata) GetThreadTsOk() (*string, bool) {
	if o == nil || IsNil(o.ThreadTs) {
		return nil, false
	}
	return o.ThreadTs, true
}

// HasThreadTs returns a boolean if a field has been set.
func (o *WebhookPayloadMessageSentMetadata) HasThreadTs() bool {
	if o != nil && !IsNil(o.ThreadTs) {
		return true
	}

	return false
}

// SetThreadTs gets a reference to the given string and assigns it to the ThreadTs field.
func (o *WebhookPayloadMessageSentMetadata) SetThreadTs(v string) {
	o.ThreadTs = &v
}

func (o WebhookPayloadMessageSentMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPayloadMessageSentMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QuotedMessageId) {
		toSerialize["quotedMessageId"] = o.QuotedMessageId
	}
	if !IsNil(o.ThreadTs) {
		toSerialize["threadTs"] = o.ThreadTs
	}
	return toSerialize, nil
}

type NullableWebhookPayloadMessageSentMetadata struct {
	value *WebhookPayloadMessageSentMetadata
	isSet bool
}

func (v NullableWebhookPayloadMessageSentMetadata) Get() *WebhookPayloadMessageSentMetadata {
	return v.value
}

func (v *NullableWebhookPayloadMessageSentMetadata) Set(val *WebhookPayloadMessageSentMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPayloadMessageSentMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPayloadMessageSentMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPayloadMessageSentMetadata(val *WebhookPayloadMessageSentMetadata) *NullableWebhookPayloadMessageSentMetadata {
	return &NullableWebhookPayloadMessageSentMetadata{value: val, isSet: true}
}

func (v NullableWebhookPayloadMessageSentMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPayloadMessageSentMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
