/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"fmt"
)

// AdTreeCampaignOptimizationGoal A single string when every ad set shares one optimization goal; a JSON array of the distinct goals when ad sets differ (never a comma-joined string); array element order is not guaranteed, treat it as an unordered set; the key is absent when no ad set carries a goal. Meta: e.g. OFFSITE_CONVERSIONS, VALUE, LEAD_GENERATION. LinkedIn: the campaign optimizationTargetType (e.g. MAX_CLICK, MAX_IMPRESSION, NONE); `NONE` with a manual costType is a campaign LinkedIn will not deliver.
type AdTreeCampaignOptimizationGoal struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AdTreeCampaignOptimizationGoal) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AdTreeCampaignOptimizationGoal)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AdTreeCampaignOptimizationGoal) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAdTreeCampaignOptimizationGoal struct {
	value *AdTreeCampaignOptimizationGoal
	isSet bool
}

func (v NullableAdTreeCampaignOptimizationGoal) Get() *AdTreeCampaignOptimizationGoal {
	return v.value
}

func (v *NullableAdTreeCampaignOptimizationGoal) Set(val *AdTreeCampaignOptimizationGoal) {
	v.value = val
	v.isSet = true
}

func (v NullableAdTreeCampaignOptimizationGoal) IsSet() bool {
	return v.isSet
}

func (v *NullableAdTreeCampaignOptimizationGoal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdTreeCampaignOptimizationGoal(val *AdTreeCampaignOptimizationGoal) *NullableAdTreeCampaignOptimizationGoal {
	return &NullableAdTreeCampaignOptimizationGoal{value: val, isSet: true}
}

func (v NullableAdTreeCampaignOptimizationGoal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdTreeCampaignOptimizationGoal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
