/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GenerateKeywordIdeas200ResponsePaging type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateKeywordIdeas200ResponsePaging{}

// GenerateKeywordIdeas200ResponsePaging struct for GenerateKeywordIdeas200ResponsePaging
type GenerateKeywordIdeas200ResponsePaging struct {
	// Cursor for the next page; null when exhausted.
	NextPageToken NullableString `json:"nextPageToken,omitempty"`
}

// NewGenerateKeywordIdeas200ResponsePaging instantiates a new GenerateKeywordIdeas200ResponsePaging object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateKeywordIdeas200ResponsePaging() *GenerateKeywordIdeas200ResponsePaging {
	this := GenerateKeywordIdeas200ResponsePaging{}
	return &this
}

// NewGenerateKeywordIdeas200ResponsePagingWithDefaults instantiates a new GenerateKeywordIdeas200ResponsePaging object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateKeywordIdeas200ResponsePagingWithDefaults() *GenerateKeywordIdeas200ResponsePaging {
	this := GenerateKeywordIdeas200ResponsePaging{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GenerateKeywordIdeas200ResponsePaging) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageToken.Get()
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GenerateKeywordIdeas200ResponsePaging) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageToken.Get(), o.NextPageToken.IsSet()
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *GenerateKeywordIdeas200ResponsePaging) HasNextPageToken() bool {
	if o != nil && o.NextPageToken.IsSet() {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given NullableString and assigns it to the NextPageToken field.
func (o *GenerateKeywordIdeas200ResponsePaging) SetNextPageToken(v string) {
	o.NextPageToken.Set(&v)
}

// SetNextPageTokenNil sets the value for NextPageToken to be an explicit nil
func (o *GenerateKeywordIdeas200ResponsePaging) SetNextPageTokenNil() {
	o.NextPageToken.Set(nil)
}

// UnsetNextPageToken ensures that no value is present for NextPageToken, not even an explicit nil
func (o *GenerateKeywordIdeas200ResponsePaging) UnsetNextPageToken() {
	o.NextPageToken.Unset()
}

func (o GenerateKeywordIdeas200ResponsePaging) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateKeywordIdeas200ResponsePaging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NextPageToken.IsSet() {
		toSerialize["nextPageToken"] = o.NextPageToken.Get()
	}
	return toSerialize, nil
}

type NullableGenerateKeywordIdeas200ResponsePaging struct {
	value *GenerateKeywordIdeas200ResponsePaging
	isSet bool
}

func (v NullableGenerateKeywordIdeas200ResponsePaging) Get() *GenerateKeywordIdeas200ResponsePaging {
	return v.value
}

func (v *NullableGenerateKeywordIdeas200ResponsePaging) Set(val *GenerateKeywordIdeas200ResponsePaging) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateKeywordIdeas200ResponsePaging) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateKeywordIdeas200ResponsePaging) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateKeywordIdeas200ResponsePaging(val *GenerateKeywordIdeas200ResponsePaging) *NullableGenerateKeywordIdeas200ResponsePaging {
	return &NullableGenerateKeywordIdeas200ResponsePaging{value: val, isSet: true}
}

func (v NullableGenerateKeywordIdeas200ResponsePaging) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateKeywordIdeas200ResponsePaging) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
