/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the InlineObject1Details type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject1Details{}

// InlineObject1Details Structured context for SDK clients that want to render their own UX. Keys vary by `reason`.
type InlineObject1Details struct {
	// How many accounts the free tier allows. Only set when reason=free_tier_exceeded.
	FreeTierAccountLimit *int32 `json:"free_tier_account_limit,omitempty"`
	// How many accounts the team currently has connected. Set when reason=free_tier_exceeded or reason=enterprise_required.
	CurrentAccountCount *int32 `json:"current_account_count,omitempty"`
	// Whether the team currently has a card on file in Stripe. Set when reason=free_tier_exceeded or reason=twitter_passthrough.
	HasPaymentMethod *bool `json:"has_payment_method,omitempty"`
	// The negotiated connected-account cap from the team's enterprise contract. Self-service teams have no cap and never receive this reason. Only set when reason=enterprise_required.
	EffectiveAccountLimit *int32 `json:"effective_account_limit,omitempty"`
}

// NewInlineObject1Details instantiates a new InlineObject1Details object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1Details() *InlineObject1Details {
	this := InlineObject1Details{}
	return &this
}

// NewInlineObject1DetailsWithDefaults instantiates a new InlineObject1Details object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1DetailsWithDefaults() *InlineObject1Details {
	this := InlineObject1Details{}
	return &this
}

// GetFreeTierAccountLimit returns the FreeTierAccountLimit field value if set, zero value otherwise.
func (o *InlineObject1Details) GetFreeTierAccountLimit() int32 {
	if o == nil || IsNil(o.FreeTierAccountLimit) {
		var ret int32
		return ret
	}
	return *o.FreeTierAccountLimit
}

// GetFreeTierAccountLimitOk returns a tuple with the FreeTierAccountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1Details) GetFreeTierAccountLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.FreeTierAccountLimit) {
		return nil, false
	}
	return o.FreeTierAccountLimit, true
}

// HasFreeTierAccountLimit returns a boolean if a field has been set.
func (o *InlineObject1Details) HasFreeTierAccountLimit() bool {
	if o != nil && !IsNil(o.FreeTierAccountLimit) {
		return true
	}

	return false
}

// SetFreeTierAccountLimit gets a reference to the given int32 and assigns it to the FreeTierAccountLimit field.
func (o *InlineObject1Details) SetFreeTierAccountLimit(v int32) {
	o.FreeTierAccountLimit = &v
}

// GetCurrentAccountCount returns the CurrentAccountCount field value if set, zero value otherwise.
func (o *InlineObject1Details) GetCurrentAccountCount() int32 {
	if o == nil || IsNil(o.CurrentAccountCount) {
		var ret int32
		return ret
	}
	return *o.CurrentAccountCount
}

// GetCurrentAccountCountOk returns a tuple with the CurrentAccountCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1Details) GetCurrentAccountCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentAccountCount) {
		return nil, false
	}
	return o.CurrentAccountCount, true
}

// HasCurrentAccountCount returns a boolean if a field has been set.
func (o *InlineObject1Details) HasCurrentAccountCount() bool {
	if o != nil && !IsNil(o.CurrentAccountCount) {
		return true
	}

	return false
}

// SetCurrentAccountCount gets a reference to the given int32 and assigns it to the CurrentAccountCount field.
func (o *InlineObject1Details) SetCurrentAccountCount(v int32) {
	o.CurrentAccountCount = &v
}

// GetHasPaymentMethod returns the HasPaymentMethod field value if set, zero value otherwise.
func (o *InlineObject1Details) GetHasPaymentMethod() bool {
	if o == nil || IsNil(o.HasPaymentMethod) {
		var ret bool
		return ret
	}
	return *o.HasPaymentMethod
}

// GetHasPaymentMethodOk returns a tuple with the HasPaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1Details) GetHasPaymentMethodOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPaymentMethod) {
		return nil, false
	}
	return o.HasPaymentMethod, true
}

// HasHasPaymentMethod returns a boolean if a field has been set.
func (o *InlineObject1Details) HasHasPaymentMethod() bool {
	if o != nil && !IsNil(o.HasPaymentMethod) {
		return true
	}

	return false
}

// SetHasPaymentMethod gets a reference to the given bool and assigns it to the HasPaymentMethod field.
func (o *InlineObject1Details) SetHasPaymentMethod(v bool) {
	o.HasPaymentMethod = &v
}

// GetEffectiveAccountLimit returns the EffectiveAccountLimit field value if set, zero value otherwise.
func (o *InlineObject1Details) GetEffectiveAccountLimit() int32 {
	if o == nil || IsNil(o.EffectiveAccountLimit) {
		var ret int32
		return ret
	}
	return *o.EffectiveAccountLimit
}

// GetEffectiveAccountLimitOk returns a tuple with the EffectiveAccountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1Details) GetEffectiveAccountLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.EffectiveAccountLimit) {
		return nil, false
	}
	return o.EffectiveAccountLimit, true
}

// HasEffectiveAccountLimit returns a boolean if a field has been set.
func (o *InlineObject1Details) HasEffectiveAccountLimit() bool {
	if o != nil && !IsNil(o.EffectiveAccountLimit) {
		return true
	}

	return false
}

// SetEffectiveAccountLimit gets a reference to the given int32 and assigns it to the EffectiveAccountLimit field.
func (o *InlineObject1Details) SetEffectiveAccountLimit(v int32) {
	o.EffectiveAccountLimit = &v
}

func (o InlineObject1Details) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject1Details) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FreeTierAccountLimit) {
		toSerialize["free_tier_account_limit"] = o.FreeTierAccountLimit
	}
	if !IsNil(o.CurrentAccountCount) {
		toSerialize["current_account_count"] = o.CurrentAccountCount
	}
	if !IsNil(o.HasPaymentMethod) {
		toSerialize["has_payment_method"] = o.HasPaymentMethod
	}
	if !IsNil(o.EffectiveAccountLimit) {
		toSerialize["effective_account_limit"] = o.EffectiveAccountLimit
	}
	return toSerialize, nil
}

type NullableInlineObject1Details struct {
	value *InlineObject1Details
	isSet bool
}

func (v NullableInlineObject1Details) Get() *InlineObject1Details {
	return v.value
}

func (v *NullableInlineObject1Details) Set(val *InlineObject1Details) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1Details) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1Details) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1Details(val *InlineObject1Details) *NullableInlineObject1Details {
	return &NullableInlineObject1Details{value: val, isSet: true}
}

func (v NullableInlineObject1Details) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1Details) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
