/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the CampaignAnalyticsResponseAnalytics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignAnalyticsResponseAnalytics{}

// CampaignAnalyticsResponseAnalytics struct for CampaignAnalyticsResponseAnalytics
type CampaignAnalyticsResponseAnalytics struct {
	Summary    *AdMetrics                                     `json:"summary,omitempty"`
	Daily      []CampaignAnalyticsResponseAnalyticsDailyInner `json:"daily,omitempty"`
	Breakdowns map[string][]map[string]interface{}            `json:"breakdowns,omitempty"`
}

// NewCampaignAnalyticsResponseAnalytics instantiates a new CampaignAnalyticsResponseAnalytics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignAnalyticsResponseAnalytics() *CampaignAnalyticsResponseAnalytics {
	this := CampaignAnalyticsResponseAnalytics{}
	return &this
}

// NewCampaignAnalyticsResponseAnalyticsWithDefaults instantiates a new CampaignAnalyticsResponseAnalytics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignAnalyticsResponseAnalyticsWithDefaults() *CampaignAnalyticsResponseAnalytics {
	this := CampaignAnalyticsResponseAnalytics{}
	return &this
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *CampaignAnalyticsResponseAnalytics) GetSummary() AdMetrics {
	if o == nil || IsNil(o.Summary) {
		var ret AdMetrics
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignAnalyticsResponseAnalytics) GetSummaryOk() (*AdMetrics, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *CampaignAnalyticsResponseAnalytics) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given AdMetrics and assigns it to the Summary field.
func (o *CampaignAnalyticsResponseAnalytics) SetSummary(v AdMetrics) {
	o.Summary = &v
}

// GetDaily returns the Daily field value if set, zero value otherwise.
func (o *CampaignAnalyticsResponseAnalytics) GetDaily() []CampaignAnalyticsResponseAnalyticsDailyInner {
	if o == nil || IsNil(o.Daily) {
		var ret []CampaignAnalyticsResponseAnalyticsDailyInner
		return ret
	}
	return o.Daily
}

// GetDailyOk returns a tuple with the Daily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignAnalyticsResponseAnalytics) GetDailyOk() ([]CampaignAnalyticsResponseAnalyticsDailyInner, bool) {
	if o == nil || IsNil(o.Daily) {
		return nil, false
	}
	return o.Daily, true
}

// HasDaily returns a boolean if a field has been set.
func (o *CampaignAnalyticsResponseAnalytics) HasDaily() bool {
	if o != nil && !IsNil(o.Daily) {
		return true
	}

	return false
}

// SetDaily gets a reference to the given []CampaignAnalyticsResponseAnalyticsDailyInner and assigns it to the Daily field.
func (o *CampaignAnalyticsResponseAnalytics) SetDaily(v []CampaignAnalyticsResponseAnalyticsDailyInner) {
	o.Daily = v
}

// GetBreakdowns returns the Breakdowns field value if set, zero value otherwise.
func (o *CampaignAnalyticsResponseAnalytics) GetBreakdowns() map[string][]map[string]interface{} {
	if o == nil || IsNil(o.Breakdowns) {
		var ret map[string][]map[string]interface{}
		return ret
	}
	return o.Breakdowns
}

// GetBreakdownsOk returns a tuple with the Breakdowns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignAnalyticsResponseAnalytics) GetBreakdownsOk() (map[string][]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Breakdowns) {
		return map[string][]map[string]interface{}{}, false
	}
	return o.Breakdowns, true
}

// HasBreakdowns returns a boolean if a field has been set.
func (o *CampaignAnalyticsResponseAnalytics) HasBreakdowns() bool {
	if o != nil && !IsNil(o.Breakdowns) {
		return true
	}

	return false
}

// SetBreakdowns gets a reference to the given map[string][]map[string]interface{} and assigns it to the Breakdowns field.
func (o *CampaignAnalyticsResponseAnalytics) SetBreakdowns(v map[string][]map[string]interface{}) {
	o.Breakdowns = v
}

func (o CampaignAnalyticsResponseAnalytics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignAnalyticsResponseAnalytics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Daily) {
		toSerialize["daily"] = o.Daily
	}
	if !IsNil(o.Breakdowns) {
		toSerialize["breakdowns"] = o.Breakdowns
	}
	return toSerialize, nil
}

type NullableCampaignAnalyticsResponseAnalytics struct {
	value *CampaignAnalyticsResponseAnalytics
	isSet bool
}

func (v NullableCampaignAnalyticsResponseAnalytics) Get() *CampaignAnalyticsResponseAnalytics {
	return v.value
}

func (v *NullableCampaignAnalyticsResponseAnalytics) Set(val *CampaignAnalyticsResponseAnalytics) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignAnalyticsResponseAnalytics) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignAnalyticsResponseAnalytics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignAnalyticsResponseAnalytics(val *CampaignAnalyticsResponseAnalytics) *NullableCampaignAnalyticsResponseAnalytics {
	return &NullableCampaignAnalyticsResponseAnalytics{value: val, isSet: true}
}

func (v NullableCampaignAnalyticsResponseAnalytics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignAnalyticsResponseAnalytics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
